<?php

namespace xSuper\VanillaBlocks\blocks;

interface VanillaBlockIds
{
    const ANCIENT_DEBRIS = 526;
    const BARREL = 458;
    const BARRIER = 416;
    const BASALT = 489;
    const POLISHED_BASALT = 490;
    const AMETHYST = 582;
    const STRIPPED_SPRUCE = 260;
    const STRIPPED_BIRCH = 261;
    const STRIPPED_JUNGLE  = 262;
    const STRIPPED_ACACIA = 263;
    const STRIPPED_DARK_OAK = 264;
    const STRIPPED_OAK = 265;
    const STRIPPED_CRIMSON = 495;
    const STRIPPED_WARPED = 496;
    const NETHER_GOLD_ORE = 543;
    const LANTERN = 463;
    const CAMPFIRE = 464;
    const BLACKSTONE = 528;
    const POLISHED_BLACKSTONE = 546;
    const CHISELED_POLISHED_BLACKSTONE = 534;
    const POLISHED_BLACKSTONE_BRICKS = 529;
    const CRACKED_POLISHED_BLACKSTONE_BRICKS = 535;
    const BLACKSTONE_WALL = 532;
    const POLISHED_BLACKSTONE_WALL = 552;
    const POLISHED_BLACKSTONE_BRICK_WALL = 533;
    const SOUL_CAMPFIRE = 545;
    const SOUL_TORCH = 523;
    const SOUL_LANTERN = 524;
    const CAMPFIRE_ITEM = 720;
    const SOUL_CAMPFIRE_ITEM = 801;
    const SOUL_SOIL = 491;
    const WARPED_DOOR = 500;
    const WARPED_DOOR_ITEM = 756;
    const CRIMSON_DOOR = 499;
    const CRIMSON_DOOR_ITEM = 755;
    const SCAFFOLDING = 420;
    const TRAPDOOR_ACACIA = 400;
    const TRAPDOOR_BIRCH = 401;
    const TRAPDOOR_CRIMSON = 501;
    const TRAPDOOR_DARK_OAK = 402;
    const TRAPDOOR_JUNGLE = 403;
    const TRAPDOOR_SPRUCE = 404;
    const TRAPDOOR_WARPED = 502;
    const STAIR_ANDESITE = 425;
    const STAIR_CRIMSON = 509;
    const STAIR_DIORITE = 426;
    const STAIR_GRANITE = 424;
    const STAIR_MOSSY_COBBLESTONE = 434;
    const STAIR_MOSSY_STONE_BRICK = 430;
    const STAIR_POLISHED_ANDESITE = 428;
    const STAIR_POLISHED_BLACKSTONE = 547;
    const STAIR_POLISHED_DIORITE = 429;
    const STAIR_POLISHED_GRANITE = 427;
    const STAIR_PRISMARINE = 257;
    const STAIR_PRISMARINE_BRICK = 259;
    const STAIR_RED_NETHERBRICK = 439;
    const STAIR_SMOOTH_QUARTZ = 440;
    const STAIR_SMOOTH_RED_SANDSTONE = 431;
    const STAIR_SMOOTH_SANDSTONE = 432;
    const STAIR_STONE = 435;
    const STAIR_WARPED = 510;
}
